// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBltYy2rXc0oF4N-Rm7aHgFo5c1eQGK4Hg',
    appId: '1:40991122857:web:f2e74196d1c79a633ed0b8',
    messagingSenderId: '40991122857',
    projectId: 'loveapp45',
    authDomain: 'loveapp45.firebaseapp.com',
    databaseURL: 'https://loveapp45-default-rtdb.firebaseio.com',
    storageBucket: 'loveapp45.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAqSzmDGceSrPmbc56fgguKEhfFGhsWCo',
    appId: '1:40991122857:android:c4ed4700b2d5b8ad3ed0b8',
    messagingSenderId: '40991122857',
    projectId: 'loveapp45',
    databaseURL: 'https://loveapp45-default-rtdb.firebaseio.com',
    storageBucket: 'loveapp45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgmSPiNdeKaa0UoxwG37PMi05DYCryJCk',
    appId: '1:40991122857:ios:c39766cf8ece61643ed0b8',
    messagingSenderId: '40991122857',
    projectId: 'loveapp45',
    databaseURL: 'https://loveapp45-default-rtdb.firebaseio.com',
    storageBucket: 'loveapp45.appspot.com',
    iosClientId: '40991122857-9e0kkbfe5os4ppqci6t3k9cl88ug78sd.apps.googleusercontent.com',
    iosBundleId: 'com.example.loveapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgmSPiNdeKaa0UoxwG37PMi05DYCryJCk',
    appId: '1:40991122857:ios:c39766cf8ece61643ed0b8',
    messagingSenderId: '40991122857',
    projectId: 'loveapp45',
    databaseURL: 'https://loveapp45-default-rtdb.firebaseio.com',
    storageBucket: 'loveapp45.appspot.com',
    iosClientId: '40991122857-9e0kkbfe5os4ppqci6t3k9cl88ug78sd.apps.googleusercontent.com',
    iosBundleId: 'com.example.loveapp',
  );
}
